-- Create SGG Code Table first (referenced by other tables)
CREATE TABLE TC_SGG (
    SGG_CD CHAR(50) PRIMARY KEY,
    SGG_CD1 CHAR(10),
    SGG_CD2 CHAR(10),
    SGG_CD3 CHAR(10),
    SGG_CD4 CHAR(10),
    SIDO_NM VARCHAR(100),
    SGG_NM VARCHAR(100),
    DONG_NM VARCHAR(100),
    RI_NM VARCHAR(100)
);

-- Code A Table with UNIQUE constraint on cd_a
CREATE TABLE TC_CODEA (
    IDX INT PRIMARY KEY,
    CD_A VARCHAR(10) UNIQUE,  -- Adding unique constraint
    CD_NM VARCHAR(255),
    CD_MEMO VARCHAR(255),
    CD_MEMO2 VARCHAR(255),
    DEL_FLAG CHAR(1),
    ORDER_NUM INT,
    PERM_WRITE CHAR(1) CHECK (PERM_WRITE IN ('Y', 'N')),
    PERM_EDIT CHAR(1) CHECK (PERM_WRITE IN ('Y', 'N')),
    PERM_DELETE CHAR(1) CHECK (PERM_WRITE IN ('Y', 'N')),
    INS_DT TIMESTAMP,
    EDIT_DT TIMESTAMP
);

-- Code B Table (references tc_codea(cd_a))
CREATE TABLE TC_CODEB (
    IDX INT PRIMARY KEY,
    CD_A VARCHAR(10) REFERENCES TC_CODEA(CD_A),  -- Now references a unique column
    CD_B VARCHAR(8),
    CD_NM VARCHAR(255),
    CD_MEMO VARCHAR(255),
    CD_MEMO2 VARCHAR(255),
    DEL_FLAG CHAR(1),
    ORDER_NUM INT,
    INS_DT TIMESTAMP,
    EDIT_DT TIMESTAMP
);

-- Traveler Master Table (references tc_sgg)
CREATE TABLE TN_TRAVELLER_MASTER (
    TRAVELER_ID VARCHAR(255) PRIMARY KEY,
    RESIDENCE_SGG_CODE VARCHAR(50),
    GENDER VARCHAR(50),
    AGE_GRP VARCHAR(50),
    EDU_NM VARCHAR(50),
    EDU_FNSH_SE VARCHAR(50),
    MARR_STTS VARCHAR(50),
    FAMILY_MEMB VARCHAR(255),
    JOB_NM VARCHAR(100),
    JOB_ETC VARCHAR(50),
    INCOME VARCHAR(50),
    HOUSE_INCOME VARCHAR(50),
    TRAVEL_TERM VARCHAR(50),
    TRAVEL_NUM INT,
    TRAVEL_LIKE_SIDO_1 VARCHAR(50),
    TRAVEL_LIKE_SGG_1 VARCHAR(50),
    TRAVEL_LIKE_SIDO_2 VARCHAR(50),
    TRAVEL_LIKE_SGG_2 VARCHAR(50),
    TRAVEL_LIKE_SIDO_3 VARCHAR(50),
    TRAVEL_LIKE_SGG_3 VARCHAR(50),
    TRAVEL_STYL_1 VARCHAR(50),
    TRAVEL_STYL_2 VARCHAR(50),
    TRAVEL_STYL_3 VARCHAR(50),
    TRAVEL_STYL_4 VARCHAR(50),
    TRAVEL_STYL_5 VARCHAR(50),
    TRAVEL_STYL_6 VARCHAR(50),
    TRAVEL_STYL_7 VARCHAR(50),
    TRAVEL_STYL_8 VARCHAR(50),
    TRAVEL_STATUS_RESIDENCE VARCHAR(50),
    TRAVEL_STATUS_DESTINATION VARCHAR(50),
    TRAVEL_STATUS_ACCOMPANY VARCHAR(50),
    travel_status_ymd VARCHAR(50),
    TRAVEL_MOTIVE_1 VARCHAR(50),
    TRAVEL_MOTIVE_2 VARCHAR(50),
    TRAVEL_MOTIVE_3 VARCHAR(50),
    TRAVEL_COMPANIONS_NUM INT
);

-- Point of Interest (POI) Master Table (references tc_sgg)
CREATE TABLE TN_POI_MASTER (
    POI_ID VARCHAR(255) PRIMARY KEY,
    POI_NM VARCHAR(255),
    BRNO VARCHAR(255),
    SGG_CD VARCHAR(255),
    ROAD_NM_ADDR VARCHAR(255),
    LOTNO_ADDR VARCHAR(255),
    ASORT_LCLASDC VARCHAR(255),
    ASORT_MLSFCDC VARCHAR(255),
    ASORT_SDASDC VARCHAR(255),
    X_COORD VARCHAR(255),
    Y_COORD VARCHAR(255),
    ROAD_NM_CD VARCHAR(255),
    LOTNO_CD VARCHAR(255)
);

-- Travel Information Table (references tn_traveller_master)
CREATE TABLE TN_TRAVEL (
    TRAVEL_ID VARCHAR(50) PRIMARY KEY,
    TRAVEL_NM VARCHAR(255),
    TRAVELER_ID VARCHAR(255),
    TRAVEL_PURPOSE VARCHAR(150),
    TRAVEL_START_YMD DATE,
    TRAVEL_END_YMD DATE,
    MVMN_NM VARCHAR(100),
    TRAVEL_PERSONA VARCHAR(150),
    TRAVEL_MISSION VARCHAR(150),
    TRAVEL_MISSION_CHECK CHAR(50),
    FOREIGN KEY (TRAVELER_ID) REFERENCES TN_TRAVELLER_MASTER(TRAVELER_ID)
);

-- Companion Information Table (references tn_travel)
CREATE TABLE TN_COMPANION_INFO (
    COMPANION_SEQ INT,
    TRAVEL_ID VARCHAR(50),
    REL_CD VARCHAR(150),
    COMPANION_GENDER VARCHAR(50),
    COMPANION_AGE_GRP VARCHAR(50),
    COMPANION_SITUATION VARCHAR(50),
    PRIMARY KEY (COMPANION_SEQ, TRAVEL_ID),  -- Composite Primary Key
    FOREIGN KEY (TRAVEL_ID) REFERENCES TN_TRAVEL(TRAVEL_ID)
);

-- Movement History Table (references tn_travel)
CREATE TABLE TN_MOVE_HIS (
    TRIP_ID VARCHAR(150),                              -- Unique trip identifier
    TRAVEL_ID VARCHAR(50),  -- Foreign key reference to tn_travel
    START_VISIT_AREA_ID VARCHAR(100),
    END_VISIT_AREA_ID VARCHAR(100) NULL,               -- Nullable as per ERD
    START_DT_MIN TIMESTAMP,
    END_DT_MIN TIMESTAMP NULL,                         -- Nullable as per ERD
    MVMN_CD_1 VARCHAR(255) NULL,                       -- Nullable as per ERD
    MVMN_CD_2 VARCHAR(255) NULL,                       -- Nullable as per ERD
    PRIMARY KEY (TRIP_ID, TRAVEL_ID),                   -- Composite Primary Key
    FOREIGN KEY (TRAVEL_ID) REFERENCES TN_TRAVEL(TRAVEL_ID)
);

-- Movement Consumption History Table (references tn_travel)
CREATE TABLE TN_MVMN_CONSUME_HIS (
    TRAVEL_ID VARCHAR(50),                           -- Reference to travel ID
    MVMN_SE VARCHAR(150),                            -- Movement segment code
    PAYMENT_SE VARCHAR(150),                         -- Payment segment code
    PAYMENT_SEQ INT,                                 -- Payment sequence
    MVMN_SE_NM VARCHAR(255) NULL,                    -- Movement segment name (nullable)
    RSVT_YN CHAR(3) NULL,                            -- Reservation indicator, nullable
    PAYMENT_NUM INT NULL,                            -- Payment number, nullable
    BRNO VARCHAR(10) NULL,                           -- Business registration number, nullable
    STORE_NM VARCHAR(255) NULL,                      -- Store name, nullable
    PAYMENT_DT TIMESTAMP NULL,                       -- Payment date, nullable
    PAYMENT_MTHD_SE VARCHAR(255) NULL,               -- Payment method, nullable
    PAYMENT_AMT_WON INT NULL,                        -- Payment amount in won, nullable
    PAYMENT_ETC TEXT NULL,                           -- Additional payment details, nullable
    PRIMARY KEY (TRAVEL_ID, MVMN_SE, PAYMENT_SE, PAYMENT_SEQ),     -- Composite Primary Key
    FOREIGN KEY (TRAVEL_ID) REFERENCES TN_TRAVEL(TRAVEL_ID)
);


-- Lodging Consumption History Table (references tn_travel)
CREATE TABLE TN_LODGE_CONSUME_HIS (
    TRAVEL_ID VARCHAR(50),                              -- Travel ID reference
    LODGING_NM VARCHAR(255),                            -- Lodging name
    LODGE_PAYMENT_SEQ INT,                              -- Lodging payment sequence
    LODGING_TYPE_CD CHAR(10) NULL,                      -- Lodging type code, nullable
    RSVT_YN CHAR(3) NULL,                               -- Reservation status (Y/N), nullable
    CHK_IN_DT_MIN TIMESTAMP NULL,                       -- Check-in date and time, nullable
    CHK_OUT_DT_MIN TIMESTAMP NULL,                      -- Check-out date and time, nullable
    PAYMENT_NUM INT NULL,                               -- Payment number, nullable
    BRNO VARCHAR(10) NULL,                              -- Business registration number, nullable
    STORE_NM VARCHAR(255) NULL,                         -- Store name, nullable
    ROAD_NM_ADDR VARCHAR(255) NULL,                     -- Road name address, nullable
    LOTNO_ADDR VARCHAR(255) NULL,                       -- Lot number address, nullable
    ROAD_NM_CD VARCHAR(255) NULL,                       -- Road name code, nullable
    LOTNO_CD VARCHAR(255) NULL,                         -- Lot number code, nullable
    PAYMENT_DT TIMESTAMP NULL,                          -- Payment date and time, nullable
    PAYMENT_MTHD_SE VARCHAR(255) NULL,                  -- Payment method, nullable
    PAYMENT_AMT_WON INT NULL,                           -- Payment amount in won, nullable
    PAYMENT_ETC TEXT NULL,                              -- Additional payment details, nullable
    PRIMARY KEY (TRAVEL_ID, LODGING_NM, LODGE_PAYMENT_SEQ),  -- Composite Primary Key
    FOREIGN KEY (TRAVEL_ID) REFERENCES TN_TRAVEL(TRAVEL_ID)
);

CREATE TABLE TN_VISIT_AREA_INFO (
    VISIT_AREA_ID VARCHAR(150),
    TRAVEL_ID VARCHAR(50),
    VISIT_ORDER INT,
    VISIT_AREA_NM VARCHAR(255),
    VISIT_START_YMD DATE,
    VISIT_END_YMD DATE,
    ROAD_NM_ADDR VARCHAR(255),
    LOTNO_ADDR VARCHAR(255),
    X_COORD VARCHAR(255),
    Y_COORD VARCHAR(255),
    ROAD_NM_CD VARCHAR(255),
    LOTNO_CD VARCHAR(255),
    POI_ID VARCHAR(255),
    POI_NM VARCHAR(255),
    RESIDENCE_TIME_MIN INT,
    VISIT_AREA_TYPE_CD VARCHAR(150),
    REVISIT_YN CHAR(1),
    VISIT_CHC_REASON_CD VARCHAR(150),
    LODGING_TYPE_CD VARCHAR(150),
    DGSTFN VARCHAR(150),
    REVISIT_INTENTION VARCHAR(150),
    RCMDTN_INTENTION VARCHAR(150),
    SGG_CD CHAR(50),
    PRIMARY KEY (VISIT_AREA_ID, TRAVEL_ID),
    FOREIGN KEY (TRAVEL_ID) REFERENCES TN_TRAVEL(TRAVEL_ID)
);

-- Activity History Table (references tn_travel)
CREATE TABLE TN_ACTIVITY_HIS (
    TRAVEL_ID VARCHAR(50),                               -- Reference to travel ID
    VISIT_AREA_ID VARCHAR(150),                          -- Visit area ID
    ACTIVITY_TYPE_CD VARCHAR(50),                        -- Activity type code
    ACTIVITY_TYPE_SEQ INT,                               -- Activity type sequence number
    ACTIVITY_ETC VARCHAR(255) NULL,                      -- Additional activity information, nullable
    ACTIVITY_DTL VARCHAR(400) NULL,                      -- Detailed activity description, nullable
    RSVT_YN CHAR(3) NULL,                                -- Reservation indicator (Y/N), nullable
    EXPND_SE VARCHAR(255) NULL,                          -- Expense segment, nullable
    ADMISSION_SE VARCHAR(255) NULL,                      -- Admission segment, nullable
    PRIMARY KEY (TRAVEL_ID, VISIT_AREA_ID, ACTIVITY_TYPE_CD, ACTIVITY_TYPE_SEQ),  -- Composite Primary Key
    FOREIGN KEY (TRAVEL_ID) REFERENCES TN_TRAVEL(TRAVEL_ID),
    FOREIGN KEY (TRAVEL_ID, VISIT_AREA_ID) 
        REFERENCES TN_VISIT_AREA_INFO(TRAVEL_ID, VISIT_AREA_ID)  -- 복합 외래키로 수정
);


-- Advertisement Consumption History Table (references tn_travel)
CREATE TABLE TN_ADV_CONSUME_HIS (
    TRAVEL_ID VARCHAR(50),                               -- Reference to travel ID
    ADV_NM VARCHAR(255),                                 -- Advertisement name
    ADV_SEQ INT,                                         -- Advertisement sequence
    PAYMENT_NUM INT NULL,                                -- Payment number, nullable
    BRNO VARCHAR(10) NULL,                               -- Business registration number, nullable
    STORE_NM VARCHAR(255) NULL,                          -- Store name, nullable
    ROAD_NM_ADDR VARCHAR(255) NULL,                      -- Road name address, nullable
    LOTNO_ADDR VARCHAR(255) NULL,                        -- Lot number address, nullable
    ROAD_NM_CD VARCHAR(255) NULL,                        -- Road name code, nullable
    LOTNO_CD VARCHAR(255) NULL,                          -- Lot number code, nullable
    PAYMENT_DT TIMESTAMP NULL,                           -- Payment date and time, nullable
    PAYMENT_MTHD_SE VARCHAR(255) NULL,                   -- Payment method, nullable
    PAYMENT_AMT_WON INT NULL,                            -- Payment amount in won, nullable
    PAYMENT_ETC TEXT NULL,                               -- Additional payment details, nullable
    SGG_CD CHAR(50) NULL,      -- SGG code, references tc_sgg table
    PRIMARY KEY (TRAVEL_ID, ADV_NM, ADV_SEQ),             -- Composite Primary Key
    FOREIGN KEY (TRAVEL_ID) REFERENCES TN_TRAVEL(TRAVEL_ID)
);

-- Activity Consumption History Table (references tn_travel)
CREATE TABLE TN_ACTIVITY_CONSUME_HIS (
    TRAVEL_ID VARCHAR(50),                               -- Reference to travel ID
    VISIT_AREA_ID VARCHAR(150),                          -- Visit area ID
    ACTIVITY_TYPE_CD VARCHAR(50),                        -- Activity type code
    ACTIVITY_TYPE_SEQ INT,                               -- Activity type sequence
    CONSUME_HIS_SEQ INT,                                 -- Consumption history sequence
    CONSUME_HIS_SNO INT,                                 -- Consumption history sub-sequence
    PAYMENT_NUM INT NULL,                                -- Payment number, nullable
    BRNO VARCHAR(10) NULL,                               -- Business registration number, nullable
    STORE_NM VARCHAR(255) NULL,                          -- Store name, nullable
    ROAD_NM_ADDR VARCHAR(255) NULL,                      -- Road name address, nullable
    LOTNO_ADDR VARCHAR(255) NULL,                        -- Lot number address, nullable
    ROAD_NM_CD VARCHAR(255) NULL,                        -- Road name code, nullable
    LOTNO_CD VARCHAR(255) NULL,                          -- Lot number code, nullable
    PAYMENT_DT TIMESTAMP NULL,                           -- Payment date and time, nullable
    PAYMENT_MTHD_SE VARCHAR(255) NULL,                   -- Payment method, nullable
    PAYMENT_AMT_WON INT NULL,                            -- Payment amount in won, nullable
    PAYMENT_ETC TEXT NULL,                               -- Additional payment details, nullable
    SGG_CD CHAR(50) NULL,      -- SGG code, references tc_sgg table
    PRIMARY KEY (TRAVEL_ID, VISIT_AREA_ID, ACTIVITY_TYPE_CD, ACTIVITY_TYPE_SEQ, CONSUME_HIS_SEQ, CONSUME_HIS_SNO),  -- Composite Primary Key
    FOREIGN KEY (TRAVEL_ID) REFERENCES TN_TRAVEL(TRAVEL_ID),
    FOREIGN KEY (TRAVEL_ID, VISIT_AREA_ID) 
        REFERENCES TN_VISIT_AREA_INFO(TRAVEL_ID, VISIT_AREA_ID),  -- 복합 외래키로 수정
    FOREIGN KEY (TRAVEL_ID, VISIT_AREA_ID, ACTIVITY_TYPE_CD, ACTIVITY_TYPE_SEQ) 
        REFERENCES TN_ACTIVITY_HIS(TRAVEL_ID, VISIT_AREA_ID, ACTIVITY_TYPE_CD, ACTIVITY_TYPE_SEQ)  -- 복합 외래키로 수정
);


-- Tour Photo Table (references tn_travel and tn_visit_area_info)
CREATE TABLE TN_TOUR_PHOTO (
    TRAVEL_ID VARCHAR(50),
    VISIT_AREA_ID VARCHAR(150),
    TOUR_PHOTO_SEQ INT,
    PHOTO_FILE_ID VARCHAR(255),
    PHOTO_FILE_NM VARCHAR(255) NULL,
    PHOTO_FILE_FRMAT VARCHAR(50) NULL,
    PHOTO_FILE_DT TIMESTAMP NULL,
    PHOTO_FILE_SAVE_PATH VARCHAR(150) NULL,
    PHOTO_FILE_RESOLUTION VARCHAR(255) NULL,
    PHOTO_FILE_X_COORD VARCHAR(255) NULL,
    PHOTO_FILE_Y_COORD VARCHAR(255) NULL,
    VISIT_AREA_NM VARCHAR(255) NULL,
    PRIMARY KEY (TRAVEL_ID, VISIT_AREA_ID, TOUR_PHOTO_SEQ, PHOTO_FILE_ID),
    FOREIGN KEY (TRAVEL_ID) REFERENCES TN_TRAVEL(TRAVEL_ID),
    FOREIGN KEY (TRAVEL_ID, VISIT_AREA_ID) 
        REFERENCES TN_VISIT_AREA_INFO(TRAVEL_ID, VISIT_AREA_ID)  -- 복합 외래키로 수정
);

COPY TC_SGG(SGG_CD, SGG_CD1, SGG_CD2, SGG_CD3, SGG_CD4, SIDO_NM, SGG_NM, DONG_NM, RI_NM) FROM '/csv_data/tc_sgg_시군구코드.csv' DELIMITER ',' CSV HEADER;

COPY TC_CODEA(IDX, CD_A, CD_NM, CD_MEMO, CD_MEMO2, DEL_FLAG, ORDER_NUM, PERM_WRITE, PERM_EDIT, PERM_DELETE, INS_DT, EDIT_DT) FROM '/csv_data/tc_codea_코드A.csv' DELIMITER ',' CSV HEADER;

COPY TC_CODEB(IDX, CD_A, CD_B, CD_NM, CD_MEMO, CD_MEMO2, DEL_FLAG, ORDER_NUM, INS_DT, EDIT_DT) FROM '/csv_data/tc_codeb_코드B.csv' DELIMITER ',' CSV HEADER;

-- train E

COPY TN_TRAVELLER_MASTER(TRAVELER_ID, RESIDENCE_SGG_CODE, GENDER, AGE_GRP, EDU_NM, EDU_FNSH_SE, MARR_STTS, FAMILY_MEMB, JOB_NM, JOB_ETC, INCOME, HOUSE_INCOME, TRAVEL_TERM, TRAVEL_NUM, TRAVEL_LIKE_SIDO_1, TRAVEL_LIKE_SGG_1, TRAVEL_LIKE_SIDO_2, TRAVEL_LIKE_SGG_2, TRAVEL_LIKE_SIDO_3, TRAVEL_LIKE_SGG_3, TRAVEL_STYL_1, TRAVEL_STYL_2, TRAVEL_STYL_3, TRAVEL_STYL_4, TRAVEL_STYL_5, TRAVEL_STYL_6, TRAVEL_STYL_7, TRAVEL_STYL_8, TRAVEL_STATUS_RESIDENCE, TRAVEL_STATUS_DESTINATION, TRAVEL_STATUS_ACCOMPANY, TRAVEL_STATUS_YMD, TRAVEL_MOTIVE_1, TRAVEL_MOTIVE_2, TRAVEL_MOTIVE_3, TRAVEL_COMPANIONS_NUM) FROM '/csv_data/train/tn_traveller_master_여행객 Master_E.csv' DELIMITER ',' CSV HEADER;
COPY TN_TRAVELLER_MASTER(TRAVELER_ID, RESIDENCE_SGG_CODE, GENDER, AGE_GRP, EDU_NM, EDU_FNSH_SE, MARR_STTS, FAMILY_MEMB, JOB_NM, JOB_ETC, INCOME, HOUSE_INCOME, TRAVEL_TERM, TRAVEL_NUM, TRAVEL_LIKE_SIDO_1, TRAVEL_LIKE_SGG_1, TRAVEL_LIKE_SIDO_2, TRAVEL_LIKE_SGG_2, TRAVEL_LIKE_SIDO_3, TRAVEL_LIKE_SGG_3, TRAVEL_STYL_1, TRAVEL_STYL_2, TRAVEL_STYL_3, TRAVEL_STYL_4, TRAVEL_STYL_5, TRAVEL_STYL_6, TRAVEL_STYL_7, TRAVEL_STYL_8, TRAVEL_STATUS_RESIDENCE, TRAVEL_STATUS_DESTINATION, TRAVEL_STATUS_ACCOMPANY, TRAVEL_STATUS_YMD, TRAVEL_MOTIVE_1, TRAVEL_MOTIVE_2, TRAVEL_MOTIVE_3, TRAVEL_COMPANIONS_NUM) FROM '/csv_data/train/tn_traveller_master_여행객 Master_F.csv' DELIMITER ',' CSV HEADER;
COPY TN_TRAVELLER_MASTER(TRAVELER_ID, RESIDENCE_SGG_CODE, GENDER, AGE_GRP, EDU_NM, EDU_FNSH_SE, MARR_STTS, FAMILY_MEMB, JOB_NM, JOB_ETC, INCOME, HOUSE_INCOME, TRAVEL_TERM, TRAVEL_NUM, TRAVEL_LIKE_SIDO_1, TRAVEL_LIKE_SGG_1, TRAVEL_LIKE_SIDO_2, TRAVEL_LIKE_SGG_2, TRAVEL_LIKE_SIDO_3, TRAVEL_LIKE_SGG_3, TRAVEL_STYL_1, TRAVEL_STYL_2, TRAVEL_STYL_3, TRAVEL_STYL_4, TRAVEL_STYL_5, TRAVEL_STYL_6, TRAVEL_STYL_7, TRAVEL_STYL_8, TRAVEL_STATUS_RESIDENCE, TRAVEL_STATUS_DESTINATION, TRAVEL_STATUS_ACCOMPANY, TRAVEL_STATUS_YMD, TRAVEL_MOTIVE_1, TRAVEL_MOTIVE_2, TRAVEL_MOTIVE_3, TRAVEL_COMPANIONS_NUM) FROM '/csv_data/train/tn_traveller_master_여행객 Master_G.csv' DELIMITER ',' CSV HEADER;
COPY TN_TRAVELLER_MASTER(TRAVELER_ID, RESIDENCE_SGG_CODE, GENDER, AGE_GRP, EDU_NM, EDU_FNSH_SE, MARR_STTS, FAMILY_MEMB, JOB_NM, JOB_ETC, INCOME, HOUSE_INCOME, TRAVEL_TERM, TRAVEL_NUM, TRAVEL_LIKE_SIDO_1, TRAVEL_LIKE_SGG_1, TRAVEL_LIKE_SIDO_2, TRAVEL_LIKE_SGG_2, TRAVEL_LIKE_SIDO_3, TRAVEL_LIKE_SGG_3, TRAVEL_STYL_1, TRAVEL_STYL_2, TRAVEL_STYL_3, TRAVEL_STYL_4, TRAVEL_STYL_5, TRAVEL_STYL_6, TRAVEL_STYL_7, TRAVEL_STYL_8, TRAVEL_STATUS_RESIDENCE, TRAVEL_STATUS_DESTINATION, TRAVEL_STATUS_ACCOMPANY, TRAVEL_STATUS_YMD, TRAVEL_MOTIVE_1, TRAVEL_MOTIVE_2, TRAVEL_MOTIVE_3, TRAVEL_COMPANIONS_NUM) FROM '/csv_data/train/tn_traveller_master_여행객 Master_H.csv' DELIMITER ',' CSV HEADER;
COPY TN_TRAVELLER_MASTER(TRAVELER_ID, RESIDENCE_SGG_CODE, GENDER, AGE_GRP, EDU_NM, EDU_FNSH_SE, MARR_STTS, FAMILY_MEMB, JOB_NM, JOB_ETC, INCOME, HOUSE_INCOME, TRAVEL_TERM, TRAVEL_NUM, TRAVEL_LIKE_SIDO_1, TRAVEL_LIKE_SGG_1, TRAVEL_LIKE_SIDO_2, TRAVEL_LIKE_SGG_2, TRAVEL_LIKE_SIDO_3, TRAVEL_LIKE_SGG_3, TRAVEL_STYL_1, TRAVEL_STYL_2, TRAVEL_STYL_3, TRAVEL_STYL_4, TRAVEL_STYL_5, TRAVEL_STYL_6, TRAVEL_STYL_7, TRAVEL_STYL_8, TRAVEL_STATUS_RESIDENCE, TRAVEL_STATUS_DESTINATION, TRAVEL_STATUS_ACCOMPANY, TRAVEL_STATUS_YMD, TRAVEL_MOTIVE_1, TRAVEL_MOTIVE_2, TRAVEL_MOTIVE_3, TRAVEL_COMPANIONS_NUM) FROM '/csv_data/val/tn_traveller_master_여행객 Master_E.csv' DELIMITER ',' CSV HEADER;
COPY TN_TRAVELLER_MASTER(TRAVELER_ID, RESIDENCE_SGG_CODE, GENDER, AGE_GRP, EDU_NM, EDU_FNSH_SE, MARR_STTS, FAMILY_MEMB, JOB_NM, JOB_ETC, INCOME, HOUSE_INCOME, TRAVEL_TERM, TRAVEL_NUM, TRAVEL_LIKE_SIDO_1, TRAVEL_LIKE_SGG_1, TRAVEL_LIKE_SIDO_2, TRAVEL_LIKE_SGG_2, TRAVEL_LIKE_SIDO_3, TRAVEL_LIKE_SGG_3, TRAVEL_STYL_1, TRAVEL_STYL_2, TRAVEL_STYL_3, TRAVEL_STYL_4, TRAVEL_STYL_5, TRAVEL_STYL_6, TRAVEL_STYL_7, TRAVEL_STYL_8, TRAVEL_STATUS_RESIDENCE, TRAVEL_STATUS_DESTINATION, TRAVEL_STATUS_ACCOMPANY, TRAVEL_STATUS_YMD, TRAVEL_MOTIVE_1, TRAVEL_MOTIVE_2, TRAVEL_MOTIVE_3, TRAVEL_COMPANIONS_NUM) FROM '/csv_data/val/tn_traveller_master_여행객 Master_F.csv' DELIMITER ',' CSV HEADER;
COPY TN_TRAVELLER_MASTER(TRAVELER_ID, RESIDENCE_SGG_CODE, GENDER, AGE_GRP, EDU_NM, EDU_FNSH_SE, MARR_STTS, FAMILY_MEMB, JOB_NM, JOB_ETC, INCOME, HOUSE_INCOME, TRAVEL_TERM, TRAVEL_NUM, TRAVEL_LIKE_SIDO_1, TRAVEL_LIKE_SGG_1, TRAVEL_LIKE_SIDO_2, TRAVEL_LIKE_SGG_2, TRAVEL_LIKE_SIDO_3, TRAVEL_LIKE_SGG_3, TRAVEL_STYL_1, TRAVEL_STYL_2, TRAVEL_STYL_3, TRAVEL_STYL_4, TRAVEL_STYL_5, TRAVEL_STYL_6, TRAVEL_STYL_7, TRAVEL_STYL_8, TRAVEL_STATUS_RESIDENCE, TRAVEL_STATUS_DESTINATION, TRAVEL_STATUS_ACCOMPANY, TRAVEL_STATUS_YMD, TRAVEL_MOTIVE_1, TRAVEL_MOTIVE_2, TRAVEL_MOTIVE_3, TRAVEL_COMPANIONS_NUM) FROM '/csv_data/val/tn_traveller_master_여행객 Master_G.csv' DELIMITER ',' CSV HEADER;
COPY TN_TRAVELLER_MASTER(TRAVELER_ID, RESIDENCE_SGG_CODE, GENDER, AGE_GRP, EDU_NM, EDU_FNSH_SE, MARR_STTS, FAMILY_MEMB, JOB_NM, JOB_ETC, INCOME, HOUSE_INCOME, TRAVEL_TERM, TRAVEL_NUM, TRAVEL_LIKE_SIDO_1, TRAVEL_LIKE_SGG_1, TRAVEL_LIKE_SIDO_2, TRAVEL_LIKE_SGG_2, TRAVEL_LIKE_SIDO_3, TRAVEL_LIKE_SGG_3, TRAVEL_STYL_1, TRAVEL_STYL_2, TRAVEL_STYL_3, TRAVEL_STYL_4, TRAVEL_STYL_5, TRAVEL_STYL_6, TRAVEL_STYL_7, TRAVEL_STYL_8, TRAVEL_STATUS_RESIDENCE, TRAVEL_STATUS_DESTINATION, TRAVEL_STATUS_ACCOMPANY, TRAVEL_STATUS_YMD, TRAVEL_MOTIVE_1, TRAVEL_MOTIVE_2, TRAVEL_MOTIVE_3, TRAVEL_COMPANIONS_NUM) FROM '/csv_data/val/tn_traveller_master_여행객 Master_H.csv' DELIMITER ',' CSV HEADER;

COPY TN_TRAVEL(TRAVEL_ID, TRAVEL_NM, TRAVELER_ID, TRAVEL_PURPOSE, TRAVEL_START_YMD, TRAVEL_END_YMD, MVMN_NM, TRAVEL_PERSONA, TRAVEL_MISSION, TRAVEL_MISSION_CHECK) FROM '/csv_data/train/tn_travel_여행_E.csv' DELIMITER ',' CSV HEADER;
COPY TN_TRAVEL(TRAVEL_ID, TRAVEL_NM, TRAVELER_ID, TRAVEL_PURPOSE, TRAVEL_START_YMD, TRAVEL_END_YMD, MVMN_NM, TRAVEL_PERSONA, TRAVEL_MISSION, TRAVEL_MISSION_CHECK) FROM '/csv_data/train/tn_travel_여행_F.csv' DELIMITER ',' CSV HEADER;
COPY TN_TRAVEL(TRAVEL_ID, TRAVEL_NM, TRAVELER_ID, TRAVEL_PURPOSE, TRAVEL_START_YMD, TRAVEL_END_YMD, MVMN_NM, TRAVEL_PERSONA, TRAVEL_MISSION, TRAVEL_MISSION_CHECK) FROM '/csv_data/train/tn_travel_여행_G.csv' DELIMITER ',' CSV HEADER;
COPY TN_TRAVEL(TRAVEL_ID, TRAVEL_NM, TRAVELER_ID, TRAVEL_PURPOSE, TRAVEL_START_YMD, TRAVEL_END_YMD, MVMN_NM, TRAVEL_PERSONA, TRAVEL_MISSION, TRAVEL_MISSION_CHECK) FROM '/csv_data/train/tn_travel_여행_H.csv' DELIMITER ',' CSV HEADER;
COPY TN_TRAVEL(TRAVEL_ID, TRAVEL_NM, TRAVELER_ID, TRAVEL_PURPOSE, TRAVEL_START_YMD, TRAVEL_END_YMD, MVMN_NM, TRAVEL_PERSONA, TRAVEL_MISSION, TRAVEL_MISSION_CHECK) FROM '/csv_data/val/tn_travel_여행_E.csv' DELIMITER ',' CSV HEADER;
COPY TN_TRAVEL(TRAVEL_ID, TRAVEL_NM, TRAVELER_ID, TRAVEL_PURPOSE, TRAVEL_START_YMD, TRAVEL_END_YMD, MVMN_NM, TRAVEL_PERSONA, TRAVEL_MISSION, TRAVEL_MISSION_CHECK) FROM '/csv_data/val/tn_travel_여행_F.csv' DELIMITER ',' CSV HEADER;
COPY TN_TRAVEL(TRAVEL_ID, TRAVEL_NM, TRAVELER_ID, TRAVEL_PURPOSE, TRAVEL_START_YMD, TRAVEL_END_YMD, MVMN_NM, TRAVEL_PERSONA, TRAVEL_MISSION, TRAVEL_MISSION_CHECK) FROM '/csv_data/val/tn_travel_여행_G.csv' DELIMITER ',' CSV HEADER;
COPY TN_TRAVEL(TRAVEL_ID, TRAVEL_NM, TRAVELER_ID, TRAVEL_PURPOSE, TRAVEL_START_YMD, TRAVEL_END_YMD, MVMN_NM, TRAVEL_PERSONA, TRAVEL_MISSION, TRAVEL_MISSION_CHECK) FROM '/csv_data/val/tn_travel_여행_H.csv' DELIMITER ',' CSV HEADER;

COPY TN_VISIT_AREA_INFO(VISIT_AREA_ID, TRAVEL_ID, VISIT_ORDER, VISIT_AREA_NM, VISIT_START_YMD, VISIT_END_YMD, ROAD_NM_ADDR, LOTNO_ADDR, X_COORD, Y_COORD, ROAD_NM_CD, LOTNO_CD, POI_ID, POI_NM, RESIDENCE_TIME_MIN, VISIT_AREA_TYPE_CD, REVISIT_YN, VISIT_CHC_REASON_CD, LODGING_TYPE_CD, DGSTFN, REVISIT_INTENTION, RCMDTN_INTENTION, SGG_CD) FROM '/csv_data/train/tn_visit_area_info_방문지정보_E.csv' DELIMITER ',' CSV HEADER;
COPY TN_VISIT_AREA_INFO(VISIT_AREA_ID, TRAVEL_ID, VISIT_ORDER, VISIT_AREA_NM, VISIT_START_YMD, VISIT_END_YMD, ROAD_NM_ADDR, LOTNO_ADDR, X_COORD, Y_COORD, ROAD_NM_CD, LOTNO_CD, POI_ID, POI_NM, RESIDENCE_TIME_MIN, VISIT_AREA_TYPE_CD, REVISIT_YN, VISIT_CHC_REASON_CD, LODGING_TYPE_CD, DGSTFN, REVISIT_INTENTION, RCMDTN_INTENTION, SGG_CD) FROM '/csv_data/train/tn_visit_area_info_방문지정보_F.csv' DELIMITER ',' CSV HEADER;
COPY TN_VISIT_AREA_INFO(VISIT_AREA_ID, TRAVEL_ID, VISIT_ORDER, VISIT_AREA_NM, VISIT_START_YMD, VISIT_END_YMD, ROAD_NM_ADDR, LOTNO_ADDR, X_COORD, Y_COORD, ROAD_NM_CD, LOTNO_CD, POI_ID, POI_NM, RESIDENCE_TIME_MIN, VISIT_AREA_TYPE_CD, REVISIT_YN, VISIT_CHC_REASON_CD, LODGING_TYPE_CD, DGSTFN, REVISIT_INTENTION, RCMDTN_INTENTION, SGG_CD) FROM '/csv_data/train/tn_visit_area_info_방문지정보_G.csv' DELIMITER ',' CSV HEADER;
COPY TN_VISIT_AREA_INFO(VISIT_AREA_ID, TRAVEL_ID, VISIT_ORDER, VISIT_AREA_NM, VISIT_START_YMD, VISIT_END_YMD, ROAD_NM_ADDR, LOTNO_ADDR, X_COORD, Y_COORD, ROAD_NM_CD, LOTNO_CD, POI_ID, POI_NM, RESIDENCE_TIME_MIN, VISIT_AREA_TYPE_CD, REVISIT_YN, VISIT_CHC_REASON_CD, LODGING_TYPE_CD, DGSTFN, REVISIT_INTENTION, RCMDTN_INTENTION, SGG_CD) FROM '/csv_data/train/tn_visit_area_info_방문지정보_H.csv' DELIMITER ',' CSV HEADER;
COPY TN_VISIT_AREA_INFO(VISIT_AREA_ID, TRAVEL_ID, VISIT_ORDER, VISIT_AREA_NM, VISIT_START_YMD, VISIT_END_YMD, ROAD_NM_ADDR, LOTNO_ADDR, X_COORD, Y_COORD, ROAD_NM_CD, LOTNO_CD, POI_ID, POI_NM, RESIDENCE_TIME_MIN, VISIT_AREA_TYPE_CD, REVISIT_YN, VISIT_CHC_REASON_CD, LODGING_TYPE_CD, DGSTFN, REVISIT_INTENTION, RCMDTN_INTENTION, SGG_CD) FROM '/csv_data/val/tn_visit_area_info_방문지정보_E.csv' DELIMITER ',' CSV HEADER;
COPY TN_VISIT_AREA_INFO(VISIT_AREA_ID, TRAVEL_ID, VISIT_ORDER, VISIT_AREA_NM, VISIT_START_YMD, VISIT_END_YMD, ROAD_NM_ADDR, LOTNO_ADDR, X_COORD, Y_COORD, ROAD_NM_CD, LOTNO_CD, POI_ID, POI_NM, RESIDENCE_TIME_MIN, VISIT_AREA_TYPE_CD, REVISIT_YN, VISIT_CHC_REASON_CD, LODGING_TYPE_CD, DGSTFN, REVISIT_INTENTION, RCMDTN_INTENTION, SGG_CD) FROM '/csv_data/val/tn_visit_area_info_방문지정보_F.csv' DELIMITER ',' CSV HEADER;
COPY TN_VISIT_AREA_INFO(VISIT_AREA_ID, TRAVEL_ID, VISIT_ORDER, VISIT_AREA_NM, VISIT_START_YMD, VISIT_END_YMD, ROAD_NM_ADDR, LOTNO_ADDR, X_COORD, Y_COORD, ROAD_NM_CD, LOTNO_CD, POI_ID, POI_NM, RESIDENCE_TIME_MIN, VISIT_AREA_TYPE_CD, REVISIT_YN, VISIT_CHC_REASON_CD, LODGING_TYPE_CD, DGSTFN, REVISIT_INTENTION, RCMDTN_INTENTION, SGG_CD) FROM '/csv_data/val/tn_visit_area_info_방문지정보_G.csv' DELIMITER ',' CSV HEADER;
COPY TN_VISIT_AREA_INFO(VISIT_AREA_ID, TRAVEL_ID, VISIT_ORDER, VISIT_AREA_NM, VISIT_START_YMD, VISIT_END_YMD, ROAD_NM_ADDR, LOTNO_ADDR, X_COORD, Y_COORD, ROAD_NM_CD, LOTNO_CD, POI_ID, POI_NM, RESIDENCE_TIME_MIN, VISIT_AREA_TYPE_CD, REVISIT_YN, VISIT_CHC_REASON_CD, LODGING_TYPE_CD, DGSTFN, REVISIT_INTENTION, RCMDTN_INTENTION, SGG_CD) FROM '/csv_data/val/tn_visit_area_info_방문지정보_H.csv' DELIMITER ',' CSV HEADER;

COPY TN_COMPANION_INFO(COMPANION_SEQ, TRAVEL_ID, REL_CD, COMPANION_GENDER, COMPANION_AGE_GRP, COMPANION_SITUATION) FROM '/csv_data/train/tn_companion_info_동반자정보_E.csv' DELIMITER ',' CSV HEADER;
COPY TN_COMPANION_INFO(COMPANION_SEQ, TRAVEL_ID, REL_CD, COMPANION_GENDER, COMPANION_AGE_GRP, COMPANION_SITUATION) FROM '/csv_data/train/tn_companion_info_동반자정보_F.csv' DELIMITER ',' CSV HEADER;
COPY TN_COMPANION_INFO(COMPANION_SEQ, TRAVEL_ID, REL_CD, COMPANION_GENDER, COMPANION_AGE_GRP, COMPANION_SITUATION) FROM '/csv_data/train/tn_companion_info_동반자정보_G.csv' DELIMITER ',' CSV HEADER;
COPY TN_COMPANION_INFO(COMPANION_SEQ, TRAVEL_ID, REL_CD, COMPANION_GENDER, COMPANION_AGE_GRP, COMPANION_SITUATION) FROM '/csv_data/train/tn_companion_info_동반자정보_H.csv' DELIMITER ',' CSV HEADER;
COPY TN_COMPANION_INFO(COMPANION_SEQ, TRAVEL_ID, REL_CD, COMPANION_GENDER, COMPANION_AGE_GRP, COMPANION_SITUATION) FROM '/csv_data/val/tn_companion_info_동반자정보_E.csv' DELIMITER ',' CSV HEADER;
COPY TN_COMPANION_INFO(COMPANION_SEQ, TRAVEL_ID, REL_CD, COMPANION_GENDER, COMPANION_AGE_GRP, COMPANION_SITUATION) FROM '/csv_data/val/tn_companion_info_동반자정보_F.csv' DELIMITER ',' CSV HEADER;
COPY TN_COMPANION_INFO(COMPANION_SEQ, TRAVEL_ID, REL_CD, COMPANION_GENDER, COMPANION_AGE_GRP, COMPANION_SITUATION) FROM '/csv_data/val/tn_companion_info_동반자정보_G.csv' DELIMITER ',' CSV HEADER;
COPY TN_COMPANION_INFO(COMPANION_SEQ, TRAVEL_ID, REL_CD, COMPANION_GENDER, COMPANION_AGE_GRP, COMPANION_SITUATION) FROM '/csv_data/val/tn_companion_info_동반자정보_H.csv' DELIMITER ',' CSV HEADER;

COPY TN_MOVE_HIS(TRAVEL_ID, TRIP_ID, START_VISIT_AREA_ID, END_VISIT_AREA_ID, START_DT_MIN, END_DT_MIN, MVMN_CD_1, MVMN_CD_2) FROM '/csv_data/train/tn_move_his_이동내역_E.csv' DELIMITER ',' CSV HEADER;
COPY TN_MOVE_HIS(TRAVEL_ID, TRIP_ID, START_VISIT_AREA_ID, END_VISIT_AREA_ID, START_DT_MIN, END_DT_MIN, MVMN_CD_1, MVMN_CD_2) FROM '/csv_data/train/tn_move_his_이동내역_F.csv' DELIMITER ',' CSV HEADER;
COPY TN_MOVE_HIS(TRAVEL_ID, TRIP_ID, START_VISIT_AREA_ID, END_VISIT_AREA_ID, START_DT_MIN, END_DT_MIN, MVMN_CD_1, MVMN_CD_2) FROM '/csv_data/train/tn_move_his_이동내역_G.csv' DELIMITER ',' CSV HEADER;
COPY TN_MOVE_HIS(TRAVEL_ID, TRIP_ID, START_VISIT_AREA_ID, END_VISIT_AREA_ID, START_DT_MIN, END_DT_MIN, MVMN_CD_1, MVMN_CD_2) FROM '/csv_data/train/tn_move_his_이동내역_H.csv' DELIMITER ',' CSV HEADER;
COPY TN_MOVE_HIS(TRAVEL_ID, TRIP_ID, START_VISIT_AREA_ID, END_VISIT_AREA_ID, START_DT_MIN, END_DT_MIN, MVMN_CD_1, MVMN_CD_2) FROM '/csv_data/val/tn_move_his_이동내역_E.csv' DELIMITER ',' CSV HEADER;
COPY TN_MOVE_HIS(TRAVEL_ID, TRIP_ID, START_VISIT_AREA_ID, END_VISIT_AREA_ID, START_DT_MIN, END_DT_MIN, MVMN_CD_1, MVMN_CD_2) FROM '/csv_data/val/tn_move_his_이동내역_F.csv' DELIMITER ',' CSV HEADER;
COPY TN_MOVE_HIS(TRAVEL_ID, TRIP_ID, START_VISIT_AREA_ID, END_VISIT_AREA_ID, START_DT_MIN, END_DT_MIN, MVMN_CD_1, MVMN_CD_2) FROM '/csv_data/val/tn_move_his_이동내역_G.csv' DELIMITER ',' CSV HEADER;
COPY TN_MOVE_HIS(TRAVEL_ID, TRIP_ID, START_VISIT_AREA_ID, END_VISIT_AREA_ID, START_DT_MIN, END_DT_MIN, MVMN_CD_1, MVMN_CD_2) FROM '/csv_data/val/tn_move_his_이동내역_H.csv' DELIMITER ',' CSV HEADER;

COPY TN_MVMN_CONSUME_HIS(TRAVEL_ID, MVMN_SE, PAYMENT_SE, PAYMENT_SEQ, MVMN_SE_NM, RSVT_YN, PAYMENT_NUM, BRNO, STORE_NM, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC) FROM '/csv_data/train/tn_mvmn_consume_his_이동수단소비내역_E.csv' DELIMITER ',' CSV HEADER;
COPY TN_MVMN_CONSUME_HIS(TRAVEL_ID, MVMN_SE, PAYMENT_SE, PAYMENT_SEQ, MVMN_SE_NM, RSVT_YN, PAYMENT_NUM, BRNO, STORE_NM, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC) FROM '/csv_data/train/tn_mvmn_consume_his_이동수단소비내역_F.csv' DELIMITER ',' CSV HEADER;
COPY TN_MVMN_CONSUME_HIS(TRAVEL_ID, MVMN_SE, PAYMENT_SE, PAYMENT_SEQ, MVMN_SE_NM, RSVT_YN, PAYMENT_NUM, BRNO, STORE_NM, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC) FROM '/csv_data/train/tn_mvmn_consume_his_이동수단소비내역_G.csv' DELIMITER ',' CSV HEADER;
COPY TN_MVMN_CONSUME_HIS(TRAVEL_ID, MVMN_SE, PAYMENT_SE, PAYMENT_SEQ, MVMN_SE_NM, RSVT_YN, PAYMENT_NUM, BRNO, STORE_NM, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC) FROM '/csv_data/train/tn_mvmn_consume_his_이동수단소비내역_H.csv' DELIMITER ',' CSV HEADER;
COPY TN_MVMN_CONSUME_HIS(TRAVEL_ID, MVMN_SE, PAYMENT_SE, PAYMENT_SEQ, MVMN_SE_NM, RSVT_YN, PAYMENT_NUM, BRNO, STORE_NM, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC) FROM '/csv_data/val/tn_mvmn_consume_his_이동수단소비내역_E.csv' DELIMITER ',' CSV HEADER;
COPY TN_MVMN_CONSUME_HIS(TRAVEL_ID, MVMN_SE, PAYMENT_SE, PAYMENT_SEQ, MVMN_SE_NM, RSVT_YN, PAYMENT_NUM, BRNO, STORE_NM, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC) FROM '/csv_data/val/tn_mvmn_consume_his_이동수단소비내역_F.csv' DELIMITER ',' CSV HEADER;
COPY TN_MVMN_CONSUME_HIS(TRAVEL_ID, MVMN_SE, PAYMENT_SE, PAYMENT_SEQ, MVMN_SE_NM, RSVT_YN, PAYMENT_NUM, BRNO, STORE_NM, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC) FROM '/csv_data/val/tn_mvmn_consume_his_이동수단소비내역_G.csv' DELIMITER ',' CSV HEADER;
COPY TN_MVMN_CONSUME_HIS(TRAVEL_ID, MVMN_SE, PAYMENT_SE, PAYMENT_SEQ, MVMN_SE_NM, RSVT_YN, PAYMENT_NUM, BRNO, STORE_NM, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC) FROM '/csv_data/val/tn_mvmn_consume_his_이동수단소비내역_H.csv' DELIMITER ',' CSV HEADER;

COPY TN_LODGE_CONSUME_HIS(TRAVEL_ID, LODGING_NM, LODGE_PAYMENT_SEQ, LODGING_TYPE_CD, RSVT_YN, CHK_IN_DT_MIN, CHK_OUT_DT_MIN, PAYMENT_NUM, BRNO, STORE_NM, ROAD_NM_ADDR, LOTNO_ADDR, ROAD_NM_CD, LOTNO_CD, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC) FROM '/csv_data/train/tn_lodge_consume_his_숙박소비내역_E.csv' DELIMITER ',' CSV HEADER;
COPY TN_LODGE_CONSUME_HIS(TRAVEL_ID, LODGING_NM, LODGE_PAYMENT_SEQ, LODGING_TYPE_CD, RSVT_YN, CHK_IN_DT_MIN, CHK_OUT_DT_MIN, PAYMENT_NUM, BRNO, STORE_NM, ROAD_NM_ADDR, LOTNO_ADDR, ROAD_NM_CD, LOTNO_CD, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC) FROM '/csv_data/train/tn_lodge_consume_his_숙박소비내역_F.csv' DELIMITER ',' CSV HEADER;
COPY TN_LODGE_CONSUME_HIS(TRAVEL_ID, LODGING_NM, LODGE_PAYMENT_SEQ, LODGING_TYPE_CD, RSVT_YN, CHK_IN_DT_MIN, CHK_OUT_DT_MIN, PAYMENT_NUM, BRNO, STORE_NM, ROAD_NM_ADDR, LOTNO_ADDR, ROAD_NM_CD, LOTNO_CD, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC) FROM '/csv_data/train/tn_lodge_consume_his_숙박소비내역_G.csv' DELIMITER ',' CSV HEADER;
COPY TN_LODGE_CONSUME_HIS(TRAVEL_ID, LODGING_NM, LODGE_PAYMENT_SEQ, LODGING_TYPE_CD, RSVT_YN, CHK_IN_DT_MIN, CHK_OUT_DT_MIN, PAYMENT_NUM, BRNO, STORE_NM, ROAD_NM_ADDR, LOTNO_ADDR, ROAD_NM_CD, LOTNO_CD, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC) FROM '/csv_data/train/tn_lodge_consume_his_숙박소비내역_H.csv' DELIMITER ',' CSV HEADER;
COPY TN_LODGE_CONSUME_HIS(TRAVEL_ID, LODGING_NM, LODGE_PAYMENT_SEQ, LODGING_TYPE_CD, RSVT_YN, CHK_IN_DT_MIN, CHK_OUT_DT_MIN, PAYMENT_NUM, BRNO, STORE_NM, ROAD_NM_ADDR, LOTNO_ADDR, ROAD_NM_CD, LOTNO_CD, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC) FROM '/csv_data/val/tn_lodge_consume_his_숙박소비내역_F.csv' DELIMITER ',' CSV HEADER;
COPY TN_LODGE_CONSUME_HIS(TRAVEL_ID, LODGING_NM, LODGE_PAYMENT_SEQ, LODGING_TYPE_CD, RSVT_YN, CHK_IN_DT_MIN, CHK_OUT_DT_MIN, PAYMENT_NUM, BRNO, STORE_NM, ROAD_NM_ADDR, LOTNO_ADDR, ROAD_NM_CD, LOTNO_CD, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC) FROM '/csv_data/val/tn_lodge_consume_his_숙박소비내역_G.csv' DELIMITER ',' CSV HEADER;
COPY TN_LODGE_CONSUME_HIS(TRAVEL_ID, LODGING_NM, LODGE_PAYMENT_SEQ, LODGING_TYPE_CD, RSVT_YN, CHK_IN_DT_MIN, CHK_OUT_DT_MIN, PAYMENT_NUM, BRNO, STORE_NM, ROAD_NM_ADDR, LOTNO_ADDR, ROAD_NM_CD, LOTNO_CD, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC) FROM '/csv_data/val/tn_lodge_consume_his_숙박소비내역_H.csv' DELIMITER ',' CSV HEADER;

COPY TN_ACTIVITY_HIS(TRAVEL_ID, VISIT_AREA_ID, ACTIVITY_TYPE_CD, ACTIVITY_TYPE_SEQ, ACTIVITY_ETC, ACTIVITY_DTL, RSVT_YN, EXPND_SE, ADMISSION_SE) FROM '/csv_data/train/tn_activity_his_활동내역_E.csv' DELIMITER ',' CSV HEADER;
COPY TN_ACTIVITY_HIS(TRAVEL_ID, VISIT_AREA_ID, ACTIVITY_TYPE_CD, ACTIVITY_TYPE_SEQ, ACTIVITY_ETC, ACTIVITY_DTL, RSVT_YN, EXPND_SE, ADMISSION_SE) FROM '/csv_data/train/tn_activity_his_활동내역_F.csv' DELIMITER ',' CSV HEADER;
COPY TN_ACTIVITY_HIS(TRAVEL_ID, VISIT_AREA_ID, ACTIVITY_TYPE_CD, ACTIVITY_TYPE_SEQ, ACTIVITY_ETC, ACTIVITY_DTL, RSVT_YN, EXPND_SE, ADMISSION_SE) FROM '/csv_data/train/tn_activity_his_활동내역_G.csv' DELIMITER ',' CSV HEADER;
COPY TN_ACTIVITY_HIS(TRAVEL_ID, VISIT_AREA_ID, ACTIVITY_TYPE_CD, ACTIVITY_TYPE_SEQ, ACTIVITY_ETC, ACTIVITY_DTL, RSVT_YN, EXPND_SE, ADMISSION_SE) FROM '/csv_data/train/tn_activity_his_활동내역_H.csv' DELIMITER ',' CSV HEADER;
COPY TN_ACTIVITY_HIS(TRAVEL_ID, VISIT_AREA_ID, ACTIVITY_TYPE_CD, ACTIVITY_TYPE_SEQ, ACTIVITY_ETC, ACTIVITY_DTL, RSVT_YN, EXPND_SE, ADMISSION_SE) FROM '/csv_data/val/tn_activity_his_활동내역_E.csv' DELIMITER ',' CSV HEADER;
COPY TN_ACTIVITY_HIS(TRAVEL_ID, VISIT_AREA_ID, ACTIVITY_TYPE_CD, ACTIVITY_TYPE_SEQ, ACTIVITY_ETC, ACTIVITY_DTL, RSVT_YN, EXPND_SE, ADMISSION_SE) FROM '/csv_data/val/tn_activity_his_활동내역_F.csv' DELIMITER ',' CSV HEADER;
COPY TN_ACTIVITY_HIS(TRAVEL_ID, VISIT_AREA_ID, ACTIVITY_TYPE_CD, ACTIVITY_TYPE_SEQ, ACTIVITY_ETC, ACTIVITY_DTL, RSVT_YN, EXPND_SE, ADMISSION_SE) FROM '/csv_data/val/tn_activity_his_활동내역_G.csv' DELIMITER ',' CSV HEADER;
COPY TN_ACTIVITY_HIS(TRAVEL_ID, VISIT_AREA_ID, ACTIVITY_TYPE_CD, ACTIVITY_TYPE_SEQ, ACTIVITY_ETC, ACTIVITY_DTL, RSVT_YN, EXPND_SE, ADMISSION_SE) FROM '/csv_data/val/tn_activity_his_활동내역_H.csv' DELIMITER ',' CSV HEADER;

COPY TN_ADV_CONSUME_HIS(TRAVEL_ID, ADV_NM, ADV_SEQ, PAYMENT_NUM, BRNO, STORE_NM, ROAD_NM_ADDR, LOTNO_ADDR, ROAD_NM_CD, LOTNO_CD, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC, SGG_CD) FROM '/csv_data/train/tn_adv_consume_his_사전소비내역_E.csv' DELIMITER ',' CSV HEADER;
COPY TN_ADV_CONSUME_HIS(TRAVEL_ID, ADV_NM, ADV_SEQ, PAYMENT_NUM, BRNO, STORE_NM, ROAD_NM_ADDR, LOTNO_ADDR, ROAD_NM_CD, LOTNO_CD, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC, SGG_CD) FROM '/csv_data/train/tn_adv_consume_his_사전소비내역_F.csv' DELIMITER ',' CSV HEADER;
COPY TN_ADV_CONSUME_HIS(TRAVEL_ID, ADV_NM, ADV_SEQ, PAYMENT_NUM, BRNO, STORE_NM, ROAD_NM_ADDR, LOTNO_ADDR, ROAD_NM_CD, LOTNO_CD, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC, SGG_CD) FROM '/csv_data/train/tn_adv_consume_his_사전소비내역_G.csv' DELIMITER ',' CSV HEADER;
COPY TN_ADV_CONSUME_HIS(TRAVEL_ID, ADV_NM, ADV_SEQ, PAYMENT_NUM, BRNO, STORE_NM, ROAD_NM_ADDR, LOTNO_ADDR, ROAD_NM_CD, LOTNO_CD, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC, SGG_CD) FROM '/csv_data/train/tn_adv_consume_his_사전소비내역_H.csv' DELIMITER ',' CSV HEADER;
COPY TN_ADV_CONSUME_HIS(TRAVEL_ID, ADV_NM, ADV_SEQ, PAYMENT_NUM, BRNO, STORE_NM, ROAD_NM_ADDR, LOTNO_ADDR, ROAD_NM_CD, LOTNO_CD, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC, SGG_CD) FROM '/csv_data/val/tn_adv_consume_his_사전소비내역_E.csv' DELIMITER ',' CSV HEADER;
COPY TN_ADV_CONSUME_HIS(TRAVEL_ID, ADV_NM, ADV_SEQ, PAYMENT_NUM, BRNO, STORE_NM, ROAD_NM_ADDR, LOTNO_ADDR, ROAD_NM_CD, LOTNO_CD, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC, SGG_CD) FROM '/csv_data/val/tn_adv_consume_his_사전소비내역_F.csv' DELIMITER ',' CSV HEADER;
COPY TN_ADV_CONSUME_HIS(TRAVEL_ID, ADV_NM, ADV_SEQ, PAYMENT_NUM, BRNO, STORE_NM, ROAD_NM_ADDR, LOTNO_ADDR, ROAD_NM_CD, LOTNO_CD, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC, SGG_CD) FROM '/csv_data/val/tn_adv_consume_his_사전소비내역_G.csv' DELIMITER ',' CSV HEADER;
COPY TN_ADV_CONSUME_HIS(TRAVEL_ID, ADV_NM, ADV_SEQ, PAYMENT_NUM, BRNO, STORE_NM, ROAD_NM_ADDR, LOTNO_ADDR, ROAD_NM_CD, LOTNO_CD, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC, SGG_CD) FROM '/csv_data/val/tn_adv_consume_his_사전소비내역_H.csv' DELIMITER ',' CSV HEADER;

COPY TN_ACTIVITY_CONSUME_HIS(TRAVEL_ID, VISIT_AREA_ID, ACTIVITY_TYPE_CD, ACTIVITY_TYPE_SEQ, CONSUME_HIS_SEQ, CONSUME_HIS_SNO, PAYMENT_NUM, BRNO, STORE_NM, ROAD_NM_ADDR, LOTNO_ADDR, ROAD_NM_CD, LOTNO_CD, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC, SGG_CD) FROM '/csv_data/train/tn_activity_consume_his_활동소비내역_E.csv' DELIMITER ',' CSV HEADER;
COPY TN_ACTIVITY_CONSUME_HIS(TRAVEL_ID, VISIT_AREA_ID, ACTIVITY_TYPE_CD, ACTIVITY_TYPE_SEQ, CONSUME_HIS_SEQ, CONSUME_HIS_SNO, PAYMENT_NUM, BRNO, STORE_NM, ROAD_NM_ADDR, LOTNO_ADDR, ROAD_NM_CD, LOTNO_CD, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC, SGG_CD) FROM '/csv_data/train/tn_activity_consume_his_활동소비내역_F.csv' DELIMITER ',' CSV HEADER;
COPY TN_ACTIVITY_CONSUME_HIS(TRAVEL_ID, VISIT_AREA_ID, ACTIVITY_TYPE_CD, ACTIVITY_TYPE_SEQ, CONSUME_HIS_SEQ, CONSUME_HIS_SNO, PAYMENT_NUM, BRNO, STORE_NM, ROAD_NM_ADDR, LOTNO_ADDR, ROAD_NM_CD, LOTNO_CD, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC, SGG_CD) FROM '/csv_data/train/tn_activity_consume_his_활동소비내역_G.csv' DELIMITER ',' CSV HEADER;
COPY TN_ACTIVITY_CONSUME_HIS(TRAVEL_ID, VISIT_AREA_ID, ACTIVITY_TYPE_CD, ACTIVITY_TYPE_SEQ, CONSUME_HIS_SEQ, CONSUME_HIS_SNO, PAYMENT_NUM, BRNO, STORE_NM, ROAD_NM_ADDR, LOTNO_ADDR, ROAD_NM_CD, LOTNO_CD, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC, SGG_CD) FROM '/csv_data/train/tn_activity_consume_his_활동소비내역_H.csv' DELIMITER ',' CSV HEADER;
COPY TN_ACTIVITY_CONSUME_HIS(TRAVEL_ID, VISIT_AREA_ID, ACTIVITY_TYPE_CD, ACTIVITY_TYPE_SEQ, CONSUME_HIS_SEQ, CONSUME_HIS_SNO, PAYMENT_NUM, BRNO, STORE_NM, ROAD_NM_ADDR, LOTNO_ADDR, ROAD_NM_CD, LOTNO_CD, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC, SGG_CD) FROM '/csv_data/val/tn_activity_consume_his_활동소비내역_E.csv' DELIMITER ',' CSV HEADER;
COPY TN_ACTIVITY_CONSUME_HIS(TRAVEL_ID, VISIT_AREA_ID, ACTIVITY_TYPE_CD, ACTIVITY_TYPE_SEQ, CONSUME_HIS_SEQ, CONSUME_HIS_SNO, PAYMENT_NUM, BRNO, STORE_NM, ROAD_NM_ADDR, LOTNO_ADDR, ROAD_NM_CD, LOTNO_CD, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC, SGG_CD) FROM '/csv_data/val/tn_activity_consume_his_활동소비내역_F.csv' DELIMITER ',' CSV HEADER;
COPY TN_ACTIVITY_CONSUME_HIS(TRAVEL_ID, VISIT_AREA_ID, ACTIVITY_TYPE_CD, ACTIVITY_TYPE_SEQ, CONSUME_HIS_SEQ, CONSUME_HIS_SNO, PAYMENT_NUM, BRNO, STORE_NM, ROAD_NM_ADDR, LOTNO_ADDR, ROAD_NM_CD, LOTNO_CD, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC, SGG_CD) FROM '/csv_data/val/tn_activity_consume_his_활동소비내역_G.csv' DELIMITER ',' CSV HEADER;
COPY TN_ACTIVITY_CONSUME_HIS(TRAVEL_ID, VISIT_AREA_ID, ACTIVITY_TYPE_CD, ACTIVITY_TYPE_SEQ, CONSUME_HIS_SEQ, CONSUME_HIS_SNO, PAYMENT_NUM, BRNO, STORE_NM, ROAD_NM_ADDR, LOTNO_ADDR, ROAD_NM_CD, LOTNO_CD, PAYMENT_DT, PAYMENT_MTHD_SE, PAYMENT_AMT_WON, PAYMENT_ETC, SGG_CD) FROM '/csv_data/val/tn_activity_consume_his_활동소비내역_H.csv' DELIMITER ',' CSV HEADER;

COPY TN_TOUR_PHOTO(TRAVEL_ID, VISIT_AREA_ID, TOUR_PHOTO_SEQ, PHOTO_FILE_ID, PHOTO_FILE_NM, PHOTO_FILE_FRMAT, PHOTO_FILE_DT, PHOTO_FILE_SAVE_PATH, PHOTO_FILE_RESOLUTION, PHOTO_FILE_X_COORD, PHOTO_FILE_Y_COORD, VISIT_AREA_NM) FROM '/csv_data/train/tn_tour_photo_관광사진_E.csv' DELIMITER ',' CSV HEADER;
COPY TN_TOUR_PHOTO(TRAVEL_ID, VISIT_AREA_ID, TOUR_PHOTO_SEQ, PHOTO_FILE_ID, PHOTO_FILE_NM, PHOTO_FILE_FRMAT, PHOTO_FILE_DT, PHOTO_FILE_SAVE_PATH, PHOTO_FILE_RESOLUTION, PHOTO_FILE_X_COORD, PHOTO_FILE_Y_COORD, VISIT_AREA_NM) FROM '/csv_data/train/tn_tour_photo_관광사진_F.csv' DELIMITER ',' CSV HEADER;
COPY TN_TOUR_PHOTO(TRAVEL_ID, VISIT_AREA_ID, TOUR_PHOTO_SEQ, PHOTO_FILE_ID, PHOTO_FILE_NM, PHOTO_FILE_FRMAT, PHOTO_FILE_DT, PHOTO_FILE_SAVE_PATH, PHOTO_FILE_RESOLUTION, PHOTO_FILE_X_COORD, PHOTO_FILE_Y_COORD, VISIT_AREA_NM) FROM '/csv_data/train/tn_tour_photo_관광사진_G.csv' DELIMITER ',' CSV HEADER;
COPY TN_TOUR_PHOTO(TRAVEL_ID, VISIT_AREA_ID, TOUR_PHOTO_SEQ, PHOTO_FILE_ID, PHOTO_FILE_NM, PHOTO_FILE_FRMAT, PHOTO_FILE_DT, PHOTO_FILE_SAVE_PATH, PHOTO_FILE_RESOLUTION, PHOTO_FILE_X_COORD, PHOTO_FILE_Y_COORD, VISIT_AREA_NM) FROM '/csv_data/train/tn_tour_photo_관광사진_H.csv' DELIMITER ',' CSV HEADER;
COPY TN_TOUR_PHOTO(TRAVEL_ID, VISIT_AREA_ID, TOUR_PHOTO_SEQ, PHOTO_FILE_ID, PHOTO_FILE_NM, PHOTO_FILE_FRMAT, PHOTO_FILE_DT, PHOTO_FILE_SAVE_PATH, PHOTO_FILE_RESOLUTION, PHOTO_FILE_X_COORD, PHOTO_FILE_Y_COORD, VISIT_AREA_NM) FROM '/csv_data/val/tn_tour_photo_관광사진_E.csv' DELIMITER ',' CSV HEADER;
COPY TN_TOUR_PHOTO(TRAVEL_ID, VISIT_AREA_ID, TOUR_PHOTO_SEQ, PHOTO_FILE_ID, PHOTO_FILE_NM, PHOTO_FILE_FRMAT, PHOTO_FILE_DT, PHOTO_FILE_SAVE_PATH, PHOTO_FILE_RESOLUTION, PHOTO_FILE_X_COORD, PHOTO_FILE_Y_COORD, VISIT_AREA_NM) FROM '/csv_data/val/tn_tour_photo_관광사진_F.csv' DELIMITER ',' CSV HEADER;
COPY TN_TOUR_PHOTO(TRAVEL_ID, VISIT_AREA_ID, TOUR_PHOTO_SEQ, PHOTO_FILE_ID, PHOTO_FILE_NM, PHOTO_FILE_FRMAT, PHOTO_FILE_DT, PHOTO_FILE_SAVE_PATH, PHOTO_FILE_RESOLUTION, PHOTO_FILE_X_COORD, PHOTO_FILE_Y_COORD, VISIT_AREA_NM) FROM '/csv_data/val/tn_tour_photo_관광사진_G.csv' DELIMITER ',' CSV HEADER;
COPY TN_TOUR_PHOTO(TRAVEL_ID, VISIT_AREA_ID, TOUR_PHOTO_SEQ, PHOTO_FILE_ID, PHOTO_FILE_NM, PHOTO_FILE_FRMAT, PHOTO_FILE_DT, PHOTO_FILE_SAVE_PATH, PHOTO_FILE_RESOLUTION, PHOTO_FILE_X_COORD, PHOTO_FILE_Y_COORD, VISIT_AREA_NM) FROM '/csv_data/val/tn_tour_photo_관광사진_H.csv' DELIMITER ',' CSV HEADER;

-- COPY tn_gps_coord(mobile_num_id, x_coord, y_coord, dt_min, travel_id) FROM 'csv_data/train/tn_gps_coord_E.csv' DELIMITER ',' CSV HEADER;
-- COPY tn_gps_coord(mobile_num_id, x_coord, y_coord, dt_min, travel_id) FROM 'csv_data/train/tn_gps_coord_F.csv' DELIMITER ',' CSV HEADER;
-- COPY tn_gps_coord(mobile_num_id, x_coord, y_coord, dt_min, travel_id) FROM 'csv_data/train/tn_gps_coord_G.csv' DELIMITER ',' CSV HEADER;
-- COPY tn_gps_coord(mobile_num_id, x_coord, y_coord, dt_min, travel_id) FROM 'csv_data/train/tn_gps_coord_H.csv' DELIMITER ',' CSV HEADER;
-- COPY tn_gps_coord(mobile_num_id, x_coord, y_coord, dt_min, travel_id) FROM 'csv_data/val/tn_gps_coord_E.csv' DELIMITER ',' CSV HEADER;
-- COPY tn_gps_coord(mobile_num_id, x_coord, y_coord, dt_min, travel_id) FROM 'csv_data/val/tn_gps_coord_F.csv' DELIMITER ',' CSV HEADER;
-- COPY tn_gps_coord(mobile_num_id, x_coord, y_coord, dt_min, travel_id) FROM 'csv_data/val/tn_gps_coord_G.csv' DELIMITER ',' CSV HEADER;
-- COPY tn_gps_coord(mobile_num_id, x_coord, y_coord, dt_min, travel_id) FROM 'csv_data/val/tn_gps_coord_H.csv' DELIMITER ',' CSV HEADER;


COPY TN_POI_MASTER(POI_ID, POI_NM, BRNO, SGG_CD, ROAD_NM_ADDR, LOTNO_ADDR, ASORT_LCLASDC, ASORT_MLSFCDC, ASORT_SDASDC, X_COORD, Y_COORD, ROAD_NM_CD, LOTNO_CD) FROM '/csv_data/tn_poi_master_POIMaster_all.csv' DELIMITER ',' CSV HEADER;
